### PR TITLE
docs: Added new voting proposal

### PR DESCRIPTION
**Pull request by EthanWakeford**
# Pull Request Template

- Fixes: 
- Closes: 

## Checklist

- [X] This PR conforms to the guidelines in [CONTRIBUTING.md](../CONTRIBUTING.md)
  - [X] It has a descriptive title
  - [X] My commits conform to the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) specification
- [X] This PR is not a duplicate of a similar PR ([how to search issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) for similar/duplicate PRs, which this is not
- [X] This PR targets the `dev` branch
- [X] I ran the pre-commit hooks or `npm test && npm lint && npm test:e2e` and all tests pass

<hr>

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Code cleanliness (removal of unnecessary comments or debug logs)

## Microservices and API Integration

- [ ] If applicable, my changes are compatible with the project's microservices architecture and API gateway integration requirements.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have made corresponding changes to the documentation
- [ ] I have removed all unnecessary comments and debug log statements
- [ ] I have linked this PR to its corresponding issue

## Screenshots (if appropriate):

Please review and suggest any further insights, improvements, or modifications needed.

### CODE REVIEW

**Comment by EthanWakeford** [comment]
# Rationale

We wanted to find a voting system that is as easy as possible for the user to vote whenever they want, with whatever level of investment in the voting as they want. Something that is easy to understand for the user to use as well as easy to score and understand how the winner is decided.

**Comment by EthanWakeford** [comment]
# New Voting System

Rank all choices with:

- strongly interested: +2
- slightly interested: +1
- neutral: 0
- slighty interested: -1
- strongly interested: -2

Every vote starts at neutral
Vote on as many or few as you want
Vote whenever you want
Votes carry over month to month
Winner is decided by a tally of all user votes for that topic/project

Winner is removed from db and previous second place becomes new first place
Current 1st, 2nd, 3rd can be displayed in real time in the UI
User can see all topics/projects and their previous votes

**Comment by zenlex** [comment]
Moving to draft status as this is largely a roadmap / sketch at this point. The starting code in here can be used as a jumping off point for whoever builds this UI out. The backend will be covered in a microservice - see #90

**Comment by helmturner** [comment]
I think we've implemented all of this functionality, so I'm going to close this as done since we have a feature tracker to associate with the closing PR

**Comment by helmturner** [comment]
On second thought, I'd like to keep the spec file around so I'll just revert the code and merge that file :)

**Review by helmturner — DISMISSED** [review]
lgtm!

**Review by helmturner — APPROVED** [review]
lgtm!

**Pull request merged**
