### PR TITLE
chore: add/configure code style toolchain

### PR DESCRIPTION
**Pull request by helmturner**
This PR adds prettier, along with a an opinionated configuration. The exact config isn't necessarily set in stone, but you can see the difference in [here](https://github.com/tulsawebdevs/website/pull/17/commits/06525d57f4573bdb12d159eb6be56723cf733082?diff=split)

If everyone is okay with this config I can revert the commit that applies the formatting and commit the config and the formatting results as separate PRs

Edit: This PR also adds and configures TypeScript and TypeScript-ESLint

### CODE REVIEW

**Review by CKCarr — APPROVED** [review]
I've reviewed the changes introduced by the Prettier configuration, the improvements in readability and cleanliness carry across the codebase. The formatting applied to files made a notable difference. I think it would be good apply this configuration.

**Review by zenlex — DISMISSED** [review]
I'm good with this, I'd just prefer single quotes and tabs over double quotes and spaces if that's agreeable. You make the call and merge it, I'll live either way. Thanks for the work!

**Comment by helmturner** [comment]
There's a bit of overlap with the style enforcement tools, so I'm just lumping them in one PR

**Comment by helmturner** [comment]
Well, it doesn't get us linting in astro... but we get TS and Prettier, so I'm cool with it. The linting rules will almost definitely need some fine tuning, but they're pretty comprehensive to start. As we get feedback we can fine tune them where appropriate.

**Review by zenlex — APPROVED** [review]
Looks good to me! thanks for all your work and TS ecosystem knowledge.

**Pull request merged**
